### ISSUE TITLE
Not working in Moodle 3.8.

### ISSUE THREAD

**Issue by coryarobbins** [LafColITS/moodle-local_course_template#18] opened 2020-05-17 23:57 UTC
Thanks for developing this. I can't seem to get it to work though. I've tried multiple times using custom regex, and I can't get the courses to actually restore the templates. I finally decided to just straight up copy the example courses listed in the wiki, but even then, when using the supplied regex, I don't get the copy of the course. It is just a default course. I've looked at the logs, and it does have a record for the template being backed up when I create the new course, but there isn't a restore record anywhere. Am I missing something?

**Comment by coryarobbins** [comment] 2020-05-18 14:44
Just a heads up...  It seems that it DOES work if I do a traditional backup and restore of my template course to a new course that begins with the shortname naming convention.  I guess there may be an issue with when shortnames are changed?  Anyway, it seems to be working.

**Comment by andyzito** [comment] 2020-05-18 15:10
Can you elaborate on that? Do you you mean that it works when you manually import the course template yourself (meaning the plugin is still broken), or that you changed something and now the plugin is functioning correctly (ie, automatically restoring course template on new course creation).

Additionally, please provide the Moodle version you are working with, the plugin version, and what your precise configuration setup is, including:
- Name, shortname, id number of the template course
- Name, shortname, id number of new courses to which the template should be applied
- The exact contents of the regex field on the plugin settings page

Thanks!

**Comment by coryarobbins** [comment] 2020-05-18 15:53
Sure!
So I had already created a template course before I installed this plugin, so I wasn't aware of the naming requirements.  I edited the course I had previously created, and I changed the short name to Template-202005.  I then added the suggested regex, and went through the steps of trying to create a course. I did the following:
**Template**
- Name: WFPS Kickstart
- Shortname: Template-202005  _was kickstart_
- ID Number of the template course was blank (didn't think that mattered)

**New Course**
- Name: PD Training
- Shortname: training
- ID Number: 42359.202005

The regex is:     /[0-9]+\.([0-9]{6})/

With this setup, it doesn't work.  The logs show a backup of the template course is triggered, but a restore never happens.  That said, it DID WORK correctly after I:

1. Do manual backup of original template course
2. Restore the manual backup into a section, keeping all settings, except
3. Setting the short name here to Template-052020. (I flipped it just to make sure there wasn't a conflict)
4. Let the restore complete.
5. Create a new course using the course ID 42359.052020

Worked perfectly at that point...  The only difference I can see is that this short name was given at the time the course was created.  The other, original one, was renamed to fit, and I went through several different number combinations to rule out issues with the particular numbers I was using.

Plugin version: v3.6.0
Moodle version: v3.8.3

Hope that helps!

**Comment by jtsafran** [comment] 2020-07-07 18:10
I am seeing a similar issue.  With full debugging on, I get an error of

```
Exception encountered in event observer '\local_course_template\observers::course_created': error/backup_user_missing_capability

    line 147 of /backup/controller/backup_controller.class.php: call to backup_check::check_security()
    line 55 of /local/course_template/classes/backup.php: call to backup_controller->__construct()
    line 48 of /local/course_template/classes/helper.php: call to local_course_template_backup::create_backup()
    line 50 of /local/course_template/classes/observers.php: call to local_course_template_helper::template_course()
    line ? of unknownfile: call to local_course_template\observers::course_created()
    line 155 of /lib/classes/event/manager.php: call to call_user_func()
    line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
    line 834 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
    line 2502 of /course/lib.php: call to core\event\base->trigger()
    line 162 of /course/edit.php: call to create_course()
```

In the case of this database, the default admin user of 2 is no longer.  In line 55 (https://github.com/LafColITS/moodle-local_course_template/blob/master/classes/backup.php#L55) the code is hard coded to use userid = 2.  Should that not be the current user id, instead?

**Comment by jtsafran** [comment] 2020-07-07 19:06
Current user doesn't work, either, when its from the CLI since the userid is 0.  Might need to pull it from the DB.  The first id listed in the value field is always the main admin (its a CSV list):

`SELECT value FROM mdl_config WHERE name = 'siteadmins';`

Not sure if there is a better way to get that value...

**Comment by mackensen** [comment] 2020-07-07 19:53
Yes, that's an invalid assumption and shouldn't be in there. `get_admin()` can retrieve the main administrator.

**Comment by jtsafran** [comment] 2020-07-09 18:43
Confirmed.  Changing

`\backup::TYPE_1COURSE, $courseid, backup::FORMAT_MOODLE, backup::INTERACTIVE_NO, backup::MODE_GENERAL, 2);`

to

`\backup::TYPE_1COURSE, $courseid, backup::FORMAT_MOODLE, backup::INTERACTIVE_NO, backup::MODE_GENERAL, get_admin()->id);`

Works beautifully.

**Comment by jtsafran** [comment] 2021-03-16 19:07
Hey all!  

Looks like the changes to branch 18-admin that fixed this issue either were not merged into main, or another merge removed the fix: https://github.com/LafColITS/moodle-local_course_template/blob/main/classes/backup.php#L56

Can that fix get added to main?

Thanks so much!

**Comment by mackensen** [comment] 2021-03-16 20:24
@jtsafran good catch, not sure how we missed that. We'll get this change out ASAP.

**Closed as completed** 2021-03-22 10:57 UTC
Labels: bug
